name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint
      continue-on-error: true
      run: |
        pip install ruff
        ruff check . --output-format=github
    - name: Type check
      continue-on-error: true
      run: |
        pip install pyright
        pyright . --outputjson
    - name: Run tests
      run: |
        pip install pytest pytest-asyncio
        pytest tests/ -v
